name: Demo mostrar entorno según la rama

on:
  push:
    branches:
      - dev
      - qa
      - main
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Mostrar rama detectada
        run: echo "Rama actual: ${{ github.ref_name }}"

      - name: Mostrar mensaje según entorno
        run: |
          if [ "${{ github.ref_name }}" = "dev" ]; then
            echo "Entorno DEV"
          elif [ "${{ github.ref_name }}" = "qa" ]; then
            echo "Entorno QA"
          elif [ "${{ github.ref_name }}" = "main" ]; then
            echo "Entorno MAIN"
          else
            echo "Entorno desconocido"
          fi

      - name: Mostrar variables y secretos
        env:
          MY_VARIABLE: ${{ vars.MY_VARIABLE }}
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "MY_VARIABLE = $MY_VARIABLE"
          echo "MY_SECRET = $MY_SECRET"

