name: Demo mostrar variables y secretos

on:
  push:
    branches:
      - dev
      - qa
      - main
  workflow_dispatch:

jobs:
  show-vars:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Mostrar variables y secretos del entorno
        env:
          MI_VARIABLE: ${{ vars.MY_VARIABLE }}
          MI_SECRETO: ${{ secrets.MY_SECRET }}
        run: |
          echo "MY_VARIABLE = $MI_VARIABLE"
          echo "MY_SECRET = $MI_SECRETO"



