name: Demo mostrar entorno según la rama

on:
  push:
    branches:
      - dev
      - qa
      - main
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Mostrar rama detectada
        run: echo 'Rama actual: ${{ github.ref_name }}'

      - name: Si es DEV
        if: github.ref_name == 'dev'
        run: echo 'Entorno DEV'

      - name: Si es QA
        if: github.ref_name == 'qa'
        run: echo 'Entorno QA'

      - name: Si es MAIN
        if: github.ref_name == 'main'
        run: echo 'Entorno MAIN'

      - name: Mostrar variable NO sensible
        run: echo 'MY_VARIABLE=${{ vars.MY_VARIABLE }}'

      - name: Mostrar secreto (enmascarado)
        run: echo 'MY_SECRET=${{ secrets.MY_SECRET }}'

